import type { Metadata } from "next";
// import { MontSerrat, DroidSerif } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layout/footer/Navbar";
import Footer from "@/components/layout/footer/Footer";

// const MontSerrat = Montserrat({
//   variable: "--font-primary",
//   subsets: ["latin"],
// });

// const DroidSerif = Droid_Serif({
//   variable: "--font-second",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "NexRover",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
